### ISSUE TITLE
[Feature Request] Built-in option to clear current database

### ISSUE THREAD

**Issue by austinzwile** [SpecterOps/BloodHound#107] opened 2023-09-18 16:37 UTC
**Description:**
I've gone through literally every feature in the BloodHound CE interface, as well as gone full out and deleted the docker images from Docker Desktop in an effort to clear the databases. But none of the above has worked to remove 

*A clear and concise description of the bug you're encountering.*

See the Description.

**Component(s) Affected:**

- [ x ] UI
- [ x ] Other - Docker / Docker Desktop

**Steps to Reproduce:**

1. Go to the BloodHound CE web interface.
  1a. Search for any "Delete/Clear Database" functionality.
  1b. Go to the "Administrator" -> "Data Quality" section. 
  1c. Note that no feature is available to delete the currently imported data from any of the above interfaces.
2. Load Docker Desktop
  2a. Delete the BloodHound CE Docker Images from Docker Desktop
  2b. Confirm they've been deleted from Docker Desktop.
  2c. Re-install BloodHound CE Docker Image using **`docker compose up`**

**Expected Behavior:**

A delete database function should be available like in regular BloodHound, or when you delete a docker instance.

**Actual Behavior:**

See description above.

*A description of what actually happened.*

**Screenshots/Code Snippets/Sample Files:**

*If applicable, add screenshots, relevant code snippets, or sample files that help illustrate the issue.*

**Environment Information:**

BloodHound CE (Latest)
Collector: [SharpHound N/A / AzureHound Latest]
OS: Windows 11 - Version 10.0.22621 Build 22621

**Browser (if UI related)** 

Firefox or Chrome

**Docker (if using Docker)** 

Docker Desktop version 4.22.0 (117440)
Docker version 24.0.5, build ced0996

**Additional Information:**

N/A

**Potential Solution (Optional):**

Add a simple "Clear Database" option in the "Data Quality" section of the 

**Related Issues:**

Haven't seen any.

**Contributor Checklist:**

- [  xxx  ] Searched the issue tracker to ensure this bug hasn't been reported before & is not already being addressed.
- [  xxx  ] I have provided clear steps to reproduce the issue.
- [  xxx  ] I have included relevant environment information details.
- [N/A] I have attached the necessary supporting documents.
- [N/A] I have checked that any JSON files I am attempting to upload to BloodHound are valid.

**Comment by StephenHinck** [comment] 2023-09-18 19:28
Hey, thank you for the request. We'll use this issue to track towards delivery of the expanded functionality in the product. In the meantime, you have a couple of options as a workaround:

If you need to restart entirely, you can run `docker compose down -v`. This will also delete the attached volumes associated with the containers in your docker compose file. A follow-up `docker compose up` will recreate all new images and volumes, and you'll start fresh.

If you just want to delete the data contained in Neo4J, but leave the configuration of users, etc in place, you can use one of the following:

- For Bash compatible shells: `docker volume rm $(docker volume ls -q | grep neo4j-data)`
- For PowerShell: `docker volume rm @(docker volume ls -q | Select-String neo4j-data)`

**Comment by austinzwile** [comment] 2023-09-18 21:11
> Hey, thank you for the request. We'll use this issue to track towards delivery of the expanded functionality in the product. In the meantime, you have a couple of options as a workaround:
> 
> If you need to restart entirely, you can run `docker compose down -v`. This will also delete the attached volumes associated with the containers in your docker compose file. A follow-up `docker compose up` will recreate all new images and volumes, and you'll start fresh.
> 
> If you just want to delete the data contained in Neo4J, but leave the configuration of users, etc in place, you can use one of the following:
> 
>     * For Bash compatible shells: `docker volume rm $(docker volume ls -q | grep neo4j-data)`
> 
>     * For PowerShell: `docker volume rm @(docker volume ls -q | Select-String neo4j-data)`

Thanks a lot! Yeah I was like, regular BH has the "Clear Database" feature, I thought I was going crazy for a bit when I searched the UI and the docs for like an hour straight trying to figure this out. Thanks a lot for the one-liners, the PowerShell one is just what I needed.

**Comment by ChrisTruncer** [comment] 2023-12-06 15:45
Can this please be added in....

**Comment by Pri3st** [comment] 2023-12-08 05:54
It would be nice for the feature to clean the "Finished Ingest Log" as well.

**Comment by Cyb3rC3lt** [comment] 2024-02-08 14:14
> Hey, thank you for the request. We'll use this issue to track towards delivery of the expanded functionality in the product. In the meantime, you have a couple of options as a workaround:
> 
> If you need to restart entirely, you can run `docker compose down -v`. This will also delete the attached volumes associated with the containers in your docker compose file. A follow-up `docker compose up` will recreate all new images and volumes, and you'll start fresh.
> 
> If you just want to delete the data contained in Neo4J, but leave the configuration of users, etc in place, you can use one of the following:
> 
> * For Bash compatible shells: `docker volume rm $(docker volume ls -q | grep neo4j-data)`
> * For PowerShell: `docker volume rm @(docker volume ls -q | Select-String neo4j-data)`

Is there a way to delete the client data but leave your custom queries that you have built up? Just ended up deleting mine using the bash command.

**Comment by StephenHinck** [comment] 2024-02-08 15:48
The bash command should only delete Neo4J data, the custom queries are stored in PostgreSQL. We're working on implementing this feature into the product and should have it ready over the next few releases.

**Comment by Cyb3rC3lt** [comment] 2024-02-08 16:01
Fair enough and good to hear that it is coming. Just for your own debugging I'll attach what commands I did incl my mistakes :-). This is everything so it's what removed the queries:

![image](https://github.com/SpecterOps/BloodHound/assets/33097451/ae41b697-e46d-4ba9-8c4a-94cdd922d61f)

![image](https://github.com/SpecterOps/BloodHound/assets/33097451/db08ff48-fcda-4601-9bcd-413dbbcabbb6)

**Comment by StephenHinck** [comment] 2024-02-08 17:32
The `docker-compose down --volumes` command will delete all volumes attached to the docker compose stack (including the PostgreSQL volume), so that's what killed the saved queries. It looks like Docker may have changed how that command works and it no longer lets you wipe volumes for downed containers. We'll see if we can find a new workaround, but expect the functionality will be delivered natively soon!

**Comment by Cyb3rC3lt** [comment] 2024-02-09 11:38
That's really good to know Stephen. Just another thing I noticed recently is that Bloodhound within Docker doesn't really like when you come back from a paused VMWare session. I have to restart docker then re-login etc and lose where I was on my graphs. 

This tip below worked perfectly. I realise this is more a Docker issue but it might be useful to some people it it was on some sort of BloodHound Wiki so they could implement it too.

https://stackoverflow.com/questions/57874055/cant-connect-to-docker-after-resuming-vm/71712089#71712089

**Comment by StephenHinck** [comment] 2024-02-09 17:50
We confirmed what's happening on that command. If you just CTRL+C the running docker containers will just be exited, so the volume will still be associated:

![image](https://github.com/SpecterOps/BloodHound/assets/12970156/4144cc5b-0aed-4f2d-88df-c444922deb1f)

If you run `docker compose down` first, they will no longer show as in use and you can remove the Neo4J volume:

![image](https://github.com/SpecterOps/BloodHound/assets/12970156/83bb6505-80c3-4ee8-bf66-bc3d95156618)

**Comment by Cyb3rC3lt** [comment] 2024-02-09 17:52
Ah fantastic info. I will add that to my notes. Thanks a million 👍🏻

**Comment by StephenHinck** [comment] 2024-03-27 15:30
This is resolved with v5.8.0

**Closed by StephenHinck** 2024-03-27 15:30 UTC
Labels: enhancement, Ticketed
