### ISSUE TITLE
localhost:8080/ui/login doesn't start

### ISSUE THREAD

**Issue by b0fhb0fh** [SpecterOps/BloodHound#34] opened 2023-08-15 17:03 UTC
Hello

I use "docker compose up" on MacOS 13.5 Ventura and Docker Desktop
All services started ok, but I can't see main UI  

Logs are here : 

% docker compose up
[+] Running 20/20
 ✔ app-db 14 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                27.9s 
   ✔ 69692152171a Pull complete                                                                                                                             5.6s 
   ✔ a31b993d5cc6 Pull complete                                                                                                                             5.8s 
   ✔ f65921886500 Pull complete                                                                                                                             5.9s 
   ✔ b9c1a94e4ca8 Pull complete                                                                                                                             5.9s 
   ✔ 435dd99ceb68 Pull complete                                                                                                                             6.5s 
   ✔ d3ee8e88c67c Pull complete                                                                                                                             6.6s 
   ✔ 84b08674f942 Pull complete                                                                                                                             6.6s 
   ✔ 7d358e850d3e Pull complete                                                                                                                             6.6s 
   ✔ adf2c63307b4 Pull complete                                                                                                                            24.2s 
   ✔ 27ff0e95dd24 Pull complete                                                                                                                            24.2s 
   ✔ 550e7b1ab95a Pull complete                                                                                                                            24.2s 
   ✔ 2287baf15bf8 Pull complete                                                                                                                            24.2s 
   ✔ 97d11a196325 Pull complete                                                                                                                            24.2s 
   ✔ 0f11fc82fe79 Pull complete                                                                                                                            24.2s 
 ✔ proxy 4 layers [⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                            15.4s 
   ✔ 7264a8db6415 Pull complete                                                                                                                             5.3s 
   ✔ af32133391e6 Pull complete                                                                                                                             5.9s 
   ✔ 1022d3e6eb6d Pull complete                                                                                                                            11.7s 
   ✔ ef9401db6143 Pull complete                                                                                                                            11.7s 
[+] Building 1.3s (17/17) FINISHED                                                                                                          docker:desktop-linux
 => [graph-db internal] load .dockerignore                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                             0.0s
 => [graph-db internal] load build definition from neo4j.Dockerfile                                                                                         0.0s
 => => transferring dockerfile: 918B                                                                                                                        0.0s
 => [graph-db internal] load metadata for docker.io/library/neo4j:4.4.0                                                                                     1.2s
 => [pgadmin internal] load .dockerignore                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                             0.0s
 => [pgadmin internal] load build definition from pgadmin.Dockerfile                                                                                        0.0s
 => => transferring dockerfile: 864B                                                                                                                        0.0s
 => [pgadmin internal] load metadata for docker.io/dpage/pgadmin4:latest                                                                                    1.2s
 => [graph-db auth] library/neo4j:pull token for registry-1.docker.io                                                                                       0.0s
 => [pgadmin auth] dpage/pgadmin4:pull token for registry-1.docker.io                                                                                       0.0s
 => [graph-db 1/3] FROM docker.io/library/neo4j:4.4.0@sha256:d0f73347c6093e474580cecf2bf3fef8988cd219d749336d513f2605b3d19d56                               0.0s
 => CACHED [graph-db 2/3] RUN echo "dbms.security.auth_enabled=false" >> /var/lib/neo4j/conf/neo4j.conf                                                     0.0s
 => CACHED [graph-db 3/3] RUN neo4j-admin memrec >> /var/lib/neo4j/conf/neo4j.conf                                                                          0.0s
 => [graph-db] exporting to image                                                                                                                           0.0s
 => => exporting layers                                                                                                                                     0.0s
 => => writing image sha256:80ed98b02fb99b490575e3c409e952498c9ddca0c3eeff8e18c9a028c69a22ba                                                                0.0s
 => => naming to docker.io/library/bloodhound-graph-db                                                                                                      0.0s
 => [pgadmin 1/3] FROM docker.io/dpage/pgadmin4@sha256:37946e4f3e7b806bed1bd3f322ccb0ba39129c0055394822eb853ff395ec9b7d                                     0.0s
 => [pgadmin internal] load build context                                                                                                                   0.0s
 => => transferring context: 494B                                                                                                                           0.0s
 => CACHED [pgadmin 2/3] COPY configs/pgadmin/servers.json /pgadmin4/servers.json                                                                           0.0s
 => CACHED [pgadmin 3/3] COPY configs/pgadmin/pgpass /pgpass                                                                                                0.0s
 => [pgadmin] exporting to image                                                                                                                            0.0s
 => => exporting layers                                                                                                                                     0.0s
 => => writing image sha256:8e0e9c13dda6aead567ec3a2556e90457ebb995f8f08f7517cc38011b89abf0c                                                                0.0s
 => => naming to docker.io/library/bloodhound-pgadmin                                                                                                       0.0s
[+] Running 7/7
 ✔ Network bloodhound_default         Created                                                                                                               0.0s 
 ✔ Volume "bloodhound_neo4j-data"     Created                                                                                                               0.0s 
 ✔ Volume "bloodhound_postgres-data"  Created                                                                                                               0.0s 
 ✔ Container bloodhound-app-db-1      Created                                                                                                               0.2s 
 ✔ Container bloodhound-graph-db-1    Created                                                                                                               0.3s 
 ✔ Container bloodhound-proxy-1       Created                                                                                                               0.2s 
 ✔ Container bloodhound-pgadmin-1     Created                                                                                                               0.1s 
Attaching to bloodhound-app-db-1, bloodhound-graph-db-1, bloodhound-pgadmin-1, bloodhound-proxy-1
bloodhound-app-db-1    | The files belonging to this database system will be owned by user "postgres".
bloodhound-app-db-1    | This user must also own the server process.
bloodhound-app-db-1    | 
bloodhound-app-db-1    | The database cluster will be initialized with locale "en_US.utf8".
bloodhound-app-db-1    | The default database encoding has accordingly been set to "UTF8".
bloodhound-app-db-1    | 
bloodhound-app-db-1    | The default text search configuration will be set to "english".
bloodhound-app-db-1    | 
bloodhound-app-db-1    | Data page checksums are disabled.
bloodhound-app-db-1    | 
bloodhound-app-db-1    | 
bloodhound-app-db-1    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
bloodhound-app-db-1    | 
bloodhound-app-db-1    | creating subdirectories ... 
bloodhound-app-db-1    | ok
bloodhound-app-db-1    | selecting dynamic shared memory implementation ... 
bloodhound-app-db-1    | posix
bloodhound-app-db-1    | selecting default max_connections ... 
bloodhound-app-db-1    | 100
bloodhound-app-db-1    | selecting default shared_buffers ... 
bloodhound-app-db-1    | 128MB
bloodhound-app-db-1    | selecting default time zone ... 
bloodhound-app-db-1    | Etc/UTC
bloodhound-app-db-1    | creating configuration files ... 
bloodhound-app-db-1    | ok
bloodhound-app-db-1    | running bootstrap script ... 
bloodhound-proxy-1     | time="2023-08-15T14:21:06Z" level=info msg="Configuration loaded from flags."
bloodhound-app-db-1    | ok
bloodhound-app-db-1    | performing post-bootstrap initialization ... 
bloodhound-app-db-1    | ok
bloodhound-app-db-1    | syncing data to disk ... 
bloodhound-app-db-1    | initdb: warning: enabling "trust" authentication for local connections
bloodhound-app-db-1    | You can change this by editing pg_hba.conf or using the option -A, or
bloodhound-app-db-1    | --auth-local and --auth-host, the next time you run initdb.
bloodhound-app-db-1    | ok
bloodhound-app-db-1    | 
bloodhound-app-db-1    | 
bloodhound-app-db-1    | Success. You can now start the database server using:
bloodhound-app-db-1    | 
bloodhound-app-db-1    |     pg_ctl -D /var/lib/postgresql/data -l logfile start
bloodhound-app-db-1    | 
bloodhound-app-db-1    | 
bloodhound-app-db-1    | waiting for server to start....
bloodhound-app-db-1    | 2023-08-15 14:21:07.338 UTC [48] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
bloodhound-app-db-1    | 2023-08-15 14:21:07.340 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
bloodhound-app-db-1    | 2023-08-15 14:21:07.347 UTC [49] LOG:  database system was shut down at 2023-08-15 14:21:07 UTC
bloodhound-app-db-1    | 2023-08-15 14:21:07.352 UTC [48] LOG:  database system is ready to accept connections
bloodhound-app-db-1    |  done
bloodhound-app-db-1    | server started
bloodhound-app-db-1    | CREATE DATABASE
bloodhound-app-db-1    | 
bloodhound-app-db-1    | 
bloodhound-app-db-1    | 
bloodhound-app-db-1    | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
bloodhound-app-db-1    | 
bloodhound-app-db-1    | 
bloodhound-app-db-1    | waiting for server to shut down...2023-08-15 14:21:07.624 UTC [48] LOG:  received fast shutdown request
bloodhound-app-db-1    | .
bloodhound-app-db-1    | 2023-08-15 14:21:07.626 UTC [48] LOG:  aborting any active transactions
bloodhound-app-db-1    | 2023-08-15 14:21:07.627 UTC [48] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
bloodhound-app-db-1    | 2023-08-15 14:21:07.629 UTC [50] LOG:  shutting down
bloodhound-app-db-1    | 2023-08-15 14:21:07.639 UTC [48] LOG:  database system is shut down
bloodhound-app-db-1    |  done
bloodhound-app-db-1    | server stopped
bloodhound-app-db-1    | 
bloodhound-app-db-1    | PostgreSQL init process complete; ready for start up.
bloodhound-app-db-1    | 
bloodhound-app-db-1    | 
bloodhound-app-db-1    | 2023-08-15 14:21:07.764 UTC [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
bloodhound-app-db-1    | 2023-08-15 14:21:07.764 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
bloodhound-app-db-1    | 2023-08-15 14:21:07.764 UTC [1] LOG:  listening on IPv6 address "::", port 5432
bloodhound-app-db-1    | 2023-08-15 14:21:07.768 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
bloodhound-app-db-1    | 2023-08-15 14:21:07.772 UTC [76] LOG:  database system was shut down at 2023-08-15 14:21:07 UTC
bloodhound-app-db-1    | 2023-08-15 14:21:07.776 UTC [1] LOG:  database system is ready to accept connections
bloodhound-graph-db-1  | Changed password for user 'neo4j'.
bloodhound-graph-db-1  | 2023-08-15 14:21:17.060+0000 INFO  Starting...
bloodhound-graph-db-1  | 2023-08-15 14:21:17.582+0000 INFO  This instance is ServerId{681da802} (681da802-8df8-4a3d-a430-9de39850ca95)
bloodhound-graph-db-1  | 2023-08-15 14:21:18.753+0000 INFO  ======== Neo4j 4.4.0 ========
bloodhound-graph-db-1  | 2023-08-15 14:21:20.406+0000 INFO  Initializing system graph model for component 'security-users' with version -1 and status UNINITIALIZED
bloodhound-graph-db-1  | 2023-08-15 14:21:20.415+0000 INFO  Setting up initial user from `auth.ini` file: neo4j
bloodhound-graph-db-1  | 2023-08-15 14:21:20.416+0000 INFO  Creating new user 'neo4j' (passwordChangeRequired=false, suspended=false)
bloodhound-graph-db-1  | 2023-08-15 14:21:20.427+0000 INFO  Setting version for 'security-users' to 3
bloodhound-graph-db-1  | 2023-08-15 14:21:20.430+0000 INFO  After initialization of system graph model component 'security-users' have version 3 and status CURRENT
bloodhound-graph-db-1  | 2023-08-15 14:21:20.435+0000 INFO  Performing postInitialization step for component 'security-users' with version 3 and status CURRENT
bloodhound-graph-db-1  | 2023-08-15 14:21:20.693+0000 INFO  Bolt enabled on 0.0.0.0:7687.
bloodhound-graph-db-1  | 2023-08-15 14:21:21.478+0000 INFO  Remote interface available at http://localhost:7474/
bloodhound-graph-db-1  | 2023-08-15 14:21:21.482+0000 INFO  id: E53006E0C18AE94DC75559A20C3E721F198BE234816A26B9CB0AE877A5A4A974
bloodhound-graph-db-1  | 2023-08-15 14:21:21.482+0000 INFO  name: system
bloodhound-graph-db-1  | 2023-08-15 14:21:21.482+0000 INFO  creationDate: 2023-08-15T14:21:19.367Z
bloodhound-graph-db-1  | 2023-08-15 14:21:21.483+0000 INFO  Started.
bloodhound-pgadmin-1   | NOTE: Configuring authentication for SERVER mode.
bloodhound-pgadmin-1   | 
bloodhound-pgadmin-1   | pgAdmin 4 - Application Initialisation
bloodhound-pgadmin-1   | ======================================
bloodhound-pgadmin-1   | 
bloodhound-pgadmin-1   | 
bloodhound-pgadmin-1   | ----------
bloodhound-pgadmin-1   | Loading servers with:
bloodhound-pgadmin-1   | User: bloodhound@specterops.io
bloodhound-pgadmin-1   | SQLite pgAdmin config: /var/lib/pgadmin/pgadmin4.db
bloodhound-pgadmin-1   | ----------
bloodhound-pgadmin-1   | Added 0 Server Group(s) and 1 Server(s).
bloodhound-pgadmin-1   | postfix/postlog: starting the Postfix mail system
bloodhound-pgadmin-1   | [2023-08-15 14:21:39 +0000] [1] [INFO] Starting gunicorn 20.1.0
bloodhound-pgadmin-1   | [2023-08-15 14:21:39 +0000] [1] [INFO] Listening at: http://[::]:5050 (1)
bloodhound-pgadmin-1   | [2023-08-15 14:21:39 +0000] [1] [INFO] Using worker: gthread
bloodhound-pgadmin-1   | [2023-08-15 14:21:39 +0000] [94] [INFO] Booting worker with pid: 94

**Comment by b0fhb0fh** [comment] 2023-08-16 05:54
% netstat -an | grep LIST
tcp46      0      0  *.5050                 *.*                    LISTEN     
tcp46      0      0  *.7687                 *.*                    LISTEN     
tcp46      0      0  *.7474                 *.*                    LISTEN     
tcp46      0      0  *.5432                 *.*                    LISTEN     
tcp46      0      0  *.8000                 *.*                    LISTEN     
tcp46      0      0  *.80                   *.*                    LISTEN     
tcp6       0      0  *.50991                *.*                    LISTEN     
tcp4       0      0  *.50991                *.*                    LISTEN     
tcp6       0      0  *.53                   *.*                    LISTEN     
tcp4       0      0  *.53                   *.*                    LISTEN     
tcp4       0      0  127.0.0.1.8021         *.*                    LISTEN     
tcp6       0      0  ::1.8021               *.*                    LISTEN     
tcp6       0      0  *.5000                 *.*                    LISTEN     
tcp4       0      0  *.5000                 *.*                    LISTEN     
tcp6       0      0  *.7000                 *.*                    LISTEN     
tcp4       0      0  *.7000                 *.*                    LISTEN     
tcp6       0      0  fe80::aede:48ff:.49164 *.*                    LISTEN     
tcp6       0      0  fe80::aede:48ff:.49163 *.*                    LISTEN     
tcp6       0      0  fe80::aede:48ff:.49162 *.*                    LISTEN     
tcp6       0      0  fe80::aede:48ff:.49161 *.*                    LISTEN     
tcp6       0      0  fe80::aede:48ff:.49160 *.*                    LISTEN     
tcp6       0      0  fe80::aede:48ff:.49159 *.*                    LISTEN     
tcp6       0      0  fe80::aede:48ff:.49158 *.*                    LISTEN     
tcp6       0      0  fe80::aede:48ff:.49157 *.*                    LISTEN     
tcp6       0      0  fe80::aede:48ff:.49156 *.*                    LISTEN     
tcp6       0      0  fe80::aede:48ff:.49155 *.*                    LISTEN     
tcp6       0      0  fe80::aede:48ff:.49154 *.*                    LISTEN

**Comment by superlinkx** [comment] 2023-08-16 22:02
You're running the local dev environment from the looks of it. If that's what you want to do, make sure to use `just bh-dev` rather than `docker compose` directly, as there are different dev profiles and you'll need to provide one to docker compose (you can see the actual docker compose command you need if you look at `bh-dev` in the `justfile`

If you were wanting to run the application in production mode, please use `examples/docker-compose` as your root folder (or copy its contents somewhere else on you filesystem if you don't want to have to work within Git.

**Comment by krizzc** [comment] 2023-08-17 14:34
This seems to be a general problem running on a MAC ?

Even using the just bh-dev version hangs upon the worker starting in pgadmin.

**Comment by superlinkx** [comment] 2023-08-17 15:56
We have a few macs on the team, I'll see if we can reproduce internally. Can you give us some general specs, and we can take a closer look?

In the meantime, I'd highly encourage using the `examples/docker-compose` system instead. It runs the production build of bloodhound and shouldn't have this issue.

**Comment by StephenHinck** [comment] 2023-08-17 22:59
I just tested and was able to run `just bh-dev` on an Intel-based Mac running Ventura 13.5.

My process was:
- Delete the `local_harnesses/build.config.json` directory which had previously been created
- Run `just init`
- Run `just bh-dev`

If you can confirm additional details about versions and error messages, we'd be happy to take a look. I'm going to close this issue in the meantime, but please feel free to respond and re-open with additional details if you're still having trouble.

**Closed by StephenHinck** 2023-08-17 22:59 UTC

**Comment by krizzc** [comment] 2023-08-18 06:53
M1 MAC 2020 16GB RAM.

No error messages it just appears to hang after the phpadmin worker process starts. If using the examples/docker-compose then there is nothing listening on port 8080 at all and using bh-dev it is there but no application is served. The best you can get a is a 404 if you connect directly to the UI container on port 3000.

**Comment by krizzc** [comment] 2023-08-18 07:38
Having upgraded go I now get an error 

```
bloodhound-bh-api-1    | go: updating go.sum: open /bloodhound/go.work.sum: read-only file system
bloodhound-bh-api-1    | failed to build, error: exit status 1
bloodhound-bh-api-1    | running...
bloodhound-bh-api-1    | /bin/sh: 1: /tmp/main: not found
```
