### ISSUE TITLE
Feature: Add Category and allowCollapse to Saved Queries

### ISSUE THREAD

**Issue by Korving-F** [SpecterOps/BloodHound#815] opened 2024-08-27 10:58 UTC
## Feature Description
I would like to organize, expand and condense custom queries from within the GUI. 

Currently custom queries are stored 'flat' which can be hard to navigate.

### Are you intending to implement this feature?
No

## Current Behavior
The current `/api/v2/saved-queries`-endpoint supports uploading of queries with a name, query and it seems since #730 also a description but not a category as far as I can tell.

The OOTB queries already try to achive something similar by using categories:
https://github.com/SpecterOps/BloodHound/blob/e88dad44567d826d3e4ea21ca1ead1774ca1cfa6/packages/javascript/bh-shared-ui/src/commonSearches.tsx#L37

## Desired Behavior
The saved_queries model and GUI need to be updated with new fields and 'collapse'-logic.

## Use Case
* Needed to make management of queries easier within the GUI.

## Additional Information
```json
{
  "name": "Some Test Seach",
  "category": "Category 1",
  "queryList": [
    {
      "final": true,
      "query": "MATCH (.....",
      "allowCollapse": true
    }
  ]
}
```
> Old datamodel allowed for collapsible categories of queries.

![image](https://github.com/user-attachments/assets/be124e36-750e-4ee3-8675-3f68a23767c2)
> Pre-shipped queries already seem to come with some category.

**Comment by StephenHinck** [comment] 2024-08-27 16:13
Closing as a duplicate of https://github.com/SpecterOps/BloodHound/issues/725

**Closed by StephenHinck** 2024-08-27 16:13 UTC
Labels: enhancement, triage

**Comment by Korving-F** [comment] 2024-08-27 16:17
I tried to search but hadn't seen that one. Thanks! :)
