### ISSUE TITLE
No execution or admin rights are shown in UI

### ISSUE THREAD

**Issue by HanseSecure** [SpecterOps/BloodHound#240] opened 2023-11-23 07:09 UTC
**Description:**

In the Community Edition no execution or admin privilege permissions are shown.

**Component(s) Affected:**

- [ ] UI

**Steps to Reproduce:**

Load the same sharphound data into the old and the new Bloodhound editions.

**Expected Behavior:**

Permissions are shown.

**Actual Behavior:**

No permssions are shown.

**Screenshots/Code Snippets/Sample Files:**

old UI
![grafik](https://github.com/SpecterOps/BloodHound/assets/24669088/66b368d5-51ed-4aac-b716-b670eed43b87)

![grafik](https://github.com/SpecterOps/BloodHound/assets/24669088/ff28962d-63ea-4c59-a913-637c9286d11d)

new UI

![grafik](https://github.com/SpecterOps/BloodHound/assets/24669088/d984923d-46a6-4285-9f68-7691c98f7889)

![grafik](https://github.com/SpecterOps/BloodHound/assets/24669088/df0c1c91-b8d5-406b-9f34-4a3da80be503)

**Environment Information:**

BloodHound: 5.1.0

Collector: 2.0.0

OS: current Kali

Browser: Firefox ESR 91.5

Docker (if using Docker): 20.10

**Comment by StephenHinck** [comment] 2023-11-27 15:55
You'll need to collect with SharpHound v2 for BHCE, while using SharpHound v1 for BloodHound Legacy - they use different schemas for the data outputs, specifically for local groups and privileges.

**Comment by HanseSecure** [comment] 2023-11-28 06:16
I gathered the information with the Sharphound Version from the Commuinty Edition (Administration->Collector)

**Comment by HanseSecure** [comment] 2023-11-30 08:30
@StephenHinck could you please reopen the issue? iam using the right collector

**Comment by emanuelduss** [comment] 2024-10-25 13:37
I have exactly the same issue. BloodHound CE does not correctly show AdminTo edges.

Here's my documentation and SharpHound files so you can reproduce it if you want.

## BloodHound Legacy

- BloodHound Version: 4.3.1
- SharpHound Version: 1.1.1
- Collection Download: [BloodHound_Legacy_4.3.1_SharpHound_1.1.1_child.testlab.local.zip](https://github.com/user-attachments/files/17522767/BloodHound_Legacy_4.3.1_SharpHound_1.1.1_child.testlab.local.zip)

Group WS1ADMINS is local admin of WS1:

<img alt="image" src="https://github.com/user-attachments/assets/84590f75-5f0f-40a9-8524-73cf558de8e5">

It's also correctly in the Neo4J DB:

![image](https://github.com/user-attachments/assets/2cb97d18-5532-4f74-8fe0-6be7e1cf9034)


Data is collected in `20241011080952_ous.json`:

```
[...]
      "GPOChanges": {
        "LocalAdmins": [
          {
            "ObjectIdentifier": "S-1-5-21-2070903584-3070904861-4042972969-1138",
            "ObjectType": "Group"
          }
        ],
        "RemoteDesktopUsers": [
          {
            "ObjectIdentifier": "S-1-5-21-2070903584-3070904861-4042972969-1138",
            "ObjectType": "Group"
          }
[...]
```

This is as expected.

## BloodHound CE

- BloodHound Version: 5.0.0
- SharpHound Version: 2.5.7
- Download Collection: [BloodHound_CE_5.0.0_SharpHound_2.5.7_child.testlab.local.zip](https://github.com/user-attachments/files/17522779/BloodHound_CE_5.0.0_SharpHound_2.5.7_child.testlab.local.zip)

Latest BloodHound CE version as of 25.10.2024:
```
$ docker compose images
CONTAINER                    REPOSITORY              TAG                 IMAGE ID            SIZE
bloodhound-ce-app-db-1       postgres                16                  bc02d8216d73        432MB
bloodhound-ce-bloodhound-1   specterops/bloodhound   latest              b949e49cb322        87.4MB
bloodhound-ce-graph-db-1     neo4j                   4.4                 f7cfcc88300d        507MB
```

Data is collected in `20241011071647_ous.json`:

```
[...]
      "GPOChanges": {
        "LocalAdmins": [
          {
            "ObjectIdentifier": "S-1-5-21-2070903584-3070904861-4042972969-1139",
            "ObjectType": "Group"
          }
        ],
        "RemoteDesktopUsers": [
          {
            "ObjectIdentifier": "S-1-5-21-2070903584-3070904861-4042972969-1139",
            "ObjectType": "Group"
          },
          {
            "ObjectIdentifier": "CHILD.TESTLAB.LOCAL-S-1-1-0",
            "ObjectType": "Group"
          }
        ],
        "DcomUsers": [],
        "PSRemoteUsers": [],
        "AffectedComputers": [
          {
            "ObjectIdentifier": "S-1-5-21-2070903584-3070904861-4042972969-1154",
            "ObjectType": "Computer"
          }
        ]
      },
[...]
```
BloodHound does not show the admin relationship:

<img alt="image" src="https://github.com/user-attachments/assets/d0fd7c28-e8f0-40a3-b88f-46e204d28530">

There is also no edge in Neo4J:

![image](https://github.com/user-attachments/assets/1b4bfc67-db75-45ae-a86e-634314fc8325)


--> This is not as expected.

**Comment by StephenHinck** [comment] 2024-10-25 15:05
Thank you for that information. This is a duplicate of https://github.com/SpecterOps/BloodHound/issues/280

**Closed by StephenHinck** 2024-10-25 15:05 UTC
Labels: bug, ticketed
