### ISSUE TITLE
SharpHound.ps1 does not produce output

### ISSUE THREAD

**Issue by Pri3st** [SpecterOps/BloodHound#260] opened 2023-12-07 20:24 UTC
**Description:**

Many times the PowerShell script will not produce the designated output file. The `.exe` ingestor works perfectly every time. Sometimes, the problem is resolved when I use the `-OutputDirectory` option.

**Comment by rvazarkar** [comment] 2024-02-02 19:27
I'm not really sure how we would go about debugging this, especially since the .ps1 script is just wrapping the .exe, so functionally there shouldn't be any real difference other than how its delivered into memory. Can you isolate a reproduction of this in a specific scenario?

**Comment by leechristensen** [comment] 2024-02-02 21:18
It could potentially be due to PowerShell tracking the current directory differently than what the .NET libs see:
<img width="828" alt="image" src="https://github.com/SpecterOps/BloodHound/assets/5449193/d82b0439-07c9-4ad4-9d86-71c300eea212">

**Comment by StephenHinck** [comment] 2024-02-22 15:45
Closing this issue as we've not heard any updates. We can always re-open with more info!

**Closed by StephenHinck** 2024-02-22 15:45 UTC
Labels: bug, triage

**Comment by robertstrom** [comment] 2024-03-28 23:37
Not sure if this is going to be seen since this issue is closed but giving it a try anyway. I have run into the same issue as described above.

In my case I opened a PowerShell shell from another shell using the `runas /user:<domain>\<user> powershell.,exe` command. When the PowerShell shell opened it opened in C:\Windows\System32. I navigated to the directory where the Sharphound.ps1 file was located and ran the commands to collect from the domain (twice because I did not see any results).

Then I ran a search for *bloodhound.zip and found that the collection files are in the C:\Windows\System32 directory. I believe that @leechristensen hit the nail on the head here.

Sharphound.ps1 / **Invoke-Bloodhound** run from the **C:\users\rstrom\Downloads\SharpHound-v2.3.3** directory

![image](https://github.com/SpecterOps/BloodHound/assets/3240205/25a3ae2b-1a0f-41a3-aa71-aafb806b9d65)

Resulting files are located in the **C:\Windows\System32** directory

![image](https://github.com/SpecterOps/BloodHound/assets/3240205/3b0c78e9-ca21-4d61-bb42-b88d91a93c6c)

The cache file ended up in System32 also

![image](https://github.com/SpecterOps/BloodHound/assets/3240205/94cbb4bd-bdcf-4feb-bc88-30f4b6e1623f)
